### ISSUE TITLE
Invalid SELECT query in SQL Server

### ISSUE THREAD

**Issue by jimhester** [r-dbi/DBItest#132]
```r
dbGetQuery(con, "SELECT * FROM (SELECT 1) a WHERE NULL IS NULL")
#>  Error in eval(substitute(expr), envir, enclos) : 
#>   <SQL> 'SELECT * FROM (SELECT 1) a WHERE NULL IS NULL'
#>   nanodbc.cpp:1587: 42000: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]No column name was specified for column 1 of 'a'
```

Tweaking the query slightly so the column has a name works though
```r
dbGetQuery(con, "SELECT * FROM (SELECT 1 a) a WHERE NULL IS NULL")
#>   a
#> 1 1
```
This is used in these tests (at least)

- quote_identifier
- quote_string_na_is_null

**Comment by krlmlr** [comment]
I'm fine with adding an explicit column name, but `SELECT 1 AS a` looks clearer to me. Would you like to submit a PR?

**Comment by krlmlr** [comment]
The query now reads ``SELECT * FROM (SELECT 1.5 AS a) "simple" `` which seems to work in SQL Server.
