### ISSUE TITLE
Specify behavior for empty or duplicate column names

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBItest#137]
Supported e.g. by RSQLite and MySQL. Need to assign a unique name, can perhaps borrow from `tibble::repair_names()`.

**Comment by krlmlr** [comment]
`odbc` seems to return a data frame with an empty column name for `SELECT 1`, CC @jimhester.

**Comment by jimhester** [comment]
I actually prefer not assigning an arbitrary name for this, if someone writes the SQL without a name presumably it is for a reason and it seems strange to bring the data into R with one.

**Comment by krlmlr** [comment]
Many DBMS drivers will do this for you anyway. We could as well avoid specifying anything here, and leave it to the caller to repair column names.

@hadley @hannesmuehleisen: Any preference?

**Comment by hannesmuehleisen** [comment]
MonetDB(Lite) will assign a column name if none is specified:
````
> str(dbGetQuery(con, "select 1, 1"))
'data.frame':	1 obs. of  2 variables:
 $ L2: int 1
 $ L4: int 1
````

**Comment by hadley** [comment]
I think we should require that the backend provides a valid data frame - i.e. no empty, NA, or duplicated column names.

**Comment by krlmlr** [comment]
Also need to make sure that `dbColumnInfo()` is consistent with that `dbFetch()` produces.
