### ISSUE TITLE
placeholders only allowed in statements if query is prefixed with PREPARE

### ISSUE THREAD

**Issue by hannesmuehleisen** [r-dbi/DBItest#145]
From ISO/IEC 9075-2:2008(E)

```
<prepare statement> ::=
  PREPARE <SQL statement name> [ <attributes specification> ]
      FROM <SQL statement variable>
```

DBItest currently does not prefix queries with PREPARE when testing dbBind. Should this not be the case? Or perhaps add tweak?

**Comment by krlmlr** [comment]
I feel this is slightly out of scope for DBI and DBItest. What does the user gain from using `PREPARE`?

Anyway, we should think about support for extensive tweaks of the SQL composed by DBItest.

**Comment by krlmlr** [comment]
`dbBind()` has `PREPARE` semantics, but actually none of RSQLite, RMariaDB or RPostgres actually use an explicit `PREPARE` -- everything happens via internal calls to the database library. Does the standard specify a syntax for placeholders that can be used in a `PREPARE` command?

**Comment by krlmlr** [comment]
Added `immediate` argument to the specs (8cc72df4c).

How do we specify prepared queries/statements in the DuckDB driver?
