### ISSUE TITLE
Prepare CRAN release

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBItest#151]
I'm planning a DBItest release, because

- CRAN asked for it because some tests don't work on R-devel
- a few changes were necessary to accommodate the new RMariaDB backend
    - I made sure these changes didn't break RSQLite (in a few cases the RSQLite implementation had to be corrected too just because the tests were insufficient)
    - I haven't looked at other backends yet

See the [NEWS](https://github.com/rstats-db/DBItest/blob/master/NEWS.md) for the most recent changes.

@hannesmuehleisen  @imanuelcostigan @jimhester @patr1ckm: Can you please double-check that your package works with the current master of DBItest? Please comment here when you think it's safe to submit DBItest to CRAN, or if there are any problems. Thanks!

(I might just submit a hotfix to CRAN to fix the urgent R-devel problems, but I'd prefer not to.)

**Comment by patr1ckm** [comment]
Our package `civis` passes R CMD check on r-devel on debian with the current master of DBItest. Should be ok.

@keithing for vis

**Comment by krlmlr** [comment]
Thanks, @patr1ckm. @hannesmuehleisen @imanuelcostigan @jimhester: Any feedback?

**Comment by hannesmuehleisen** [comment]
Did try with the dev version and the gc() issue is gone.

**Comment by krlmlr** [comment]
Submitting hotfix that just fixes the `gc()` problems, because CRAN is threatening to remove packages. Can't submit current `master` yet. Sorry for being slow.
