### ISSUE TITLE
with_remove_test_table() fails for bigrquery

### ISSUE THREAD

**Issue by hadley** [r-dbi/DBItest#168]
Because legacy sql does not support "DROP" sql. Is there a reason this doesn't call `DBI::dbRemoveTable()`? I'd also recommend not wrapping this is in a silent try, as it makes debugging harder.

**Comment by krlmlr** [comment]
You can't test creating tables without a way to remove tables, and vice versa. The `DROP` was an attempt to escape this loop, but I agree that it's better to call `dbRemoveTable()`.

**Comment by hadley** [comment]
Similarly, any test that uses `CREATE` fails on bigquery.

**Comment by krlmlr** [comment]
bigrquery currently doesn't use DBItest.
