### ISSUE TITLE
`get_query_n_bad` should use named parameter to `dbGetQuery`

### ISSUE THREAD

**Issue by hannesmuehleisen** [r-dbi/DBItest#177]
`get_query_n_bad` calls `dbGetQuery(con, query, -2)` etc. However, in DBI the definition of `dbGetQuery` is ` function(conn, statement, ..., n = -1L) {`. Hence, `n` is never modified for the default implementation.

**Comment by krlmlr** [comment]
Thanks. In the dev version, I see:

https://github.com/r-dbi/DBItest/blob/9e0e1236274eb2cd85f97b15dfb1d713a71e2c51/R/spec-result-get-query.R#L82-L91
