### ISSUE TITLE
Handling of timestamps without time zones

### ISSUE THREAD

**Issue by hannesmuehleisen** [r-dbi/DBItest#178]
The `roundtrip_timestamp` test explicitly allows the roundtrip timestamps to carry a different time zone when returned, which makes a lot of sense. For example, in DuckDB, timestamps are always stored as UTC and are returned accordingly. However, the `local` column does not have a time zone (`NULL` is set). The `transform` function does convert the returned columns _except_ the `local` column, and because DuckDB returns this as UTC as well, the test fails. 

I think the result transformer should also convert the `local` column, or am I missing something?

See https://github.com/r-dbi/DBItest/blob/d1fddecdb16c53f9e7bf21fe01c50f33085ad5ce/R/spec-sql-write-table.R#L548

**Comment by krlmlr** [comment]
Specifically, https://github.com/r-dbi/DBItest/blob/d1fddecdb16c53f9e7bf21fe01c50f33085ad5ce/R/spec-sql-write-table.R#L575 looks odd. We should transform both input and output before comparing in this case.

**Comment by krlmlr** [comment]
The `"roundtrip_timestamp"` test now passes in duckdb.
