### ISSUE TITLE
as.character conversion expected to give full decimal representation but it does not

### ISSUE THREAD

**Issue by martinstuder** [r-dbi/DBItest#202]
https://github.com/r-dbi/DBItest/blob/cb4761311ed8106c69d32869f5fd52a202d23566/R/spec-sql-append-table.R#L181-L183

According to the comment the `as.character` conversion is expected to give the full decimal representation but it does not, so tests are expected to fail:
```
> as.character(c(-1e14, 1e15))
[1] "-1e+14" "1e+15"
```
Not sure whether the intention was to use the same conversion as further above: `format(..., scientific = FALSE)`

**Comment by krlmlr** [comment]
Thanks. The `"bit64"` class implements the behavior described in the specification, see RPostgres for an example. Your observed behavior happens if you use `numeric` as container.

**Comment by martinstuder** [comment]
Ok, thanks for the clarification.
