### ISSUE TITLE
overwrite_missing_table spec should use iris_in instead of iris in dbWriteTable

### ISSUE THREAD

**Issue by martinstuder** [r-dbi/DBItest#210]
https://github.com/r-dbi/DBItest/blob/7bd0ae10a41a76a19ad1ca4bb6a22d12706e2de0/R/spec-sql-write-table.R#L151-L154

The call to `dbWriteTable` above should use `iris_in` instead of `iris` since the `expect_equal_df` call uses `iris_in`.

**Comment by krlmlr** [comment]
Thanks. What problems are you seeing with the current implementation?

**Comment by martinstuder** [comment]
@krlmlr I was investigating a failure in that test case (`overwrite_table_missing`) that I thought was related to a difference between `datasets::iris` and the result of `DBItest:::get_iris`. It turns out the test case actually passes and the issue was a different one unrelated to `DBItest`. If I understand the test case correctly, it would still seem safer to use `iris_in` in case the definition of `DBItest:::get_iris` should change.

Partially related to that may be that `DBItest:::get_iris` currently includes an `as.character` conversion on `Species` that doesn't have any effect since it performs the conversion on a local copy of `iris` instead of `datasets_iris`:

https://github.com/r-dbi/DBItest/blob/3c377622f1953f17894431dc451d74ee1225b404/R/utils.R#L121

**Comment by krlmlr** [comment]
Good catch, thanks!
