### ISSUE TITLE
Remove uses of expect_is() to support compatibility with testthat 3e

### ISSUE THREAD

**Issue by michaelquinn32** [r-dbi/DBItest#231]
I'm updating R packages to use testthat third edition, and I've noticed that DBItest is still using expect_is() in a few locations. Would you like a PR to clean this up?

**Comment by krlmlr** [comment]
This would be awesome, thanks! Is this still an issue with the current development version?

**Comment by michaelquinn32** [comment]
It seem so:
https://github.com/r-dbi/DBItest/search?q=expect_is

There are also calls to expect_that() that could be fixed as well:
https://github.com/r-dbi/DBItest/search?q=expect_that

**Comment by michaelquinn32** [comment]
Maybe I misunderstood what dev version means, but it's at least there in the 1.7.1 branch. See:
https://github.com/r-dbi/DBItest/blob/cran-1.7.1/R/spec-meta-get-statement.R
