### ISSUE TITLE
DBItest causes warning on testthat 3rd edition (context() is deprecated)

### ISSUE THREAD

**Issue by MichaelChirico** [r-dbi/DBItest#263]
[`testthat::context()`]() is deprecated in the 3rd edition, but it's always called here:

https://github.com/r-dbi/DBItest/blob/e9286cb4bb963d8cbd5491fda9fcc1e29997a777/R/run.R#L15

Should that simply be escaped?

```r
if (testthat::edition_get() < 3) context(test_context)
```

Or given the current version requirement on testthat, more robustly:

```r
if (packageVersion("testthat") < "3.0.0" || testthat::edition_get() < 3) context(test_context)
```

Happy to file a PR for whatever's the desired behavior.

**Comment by krlmlr** [comment]
Thanks. I'm aware of that, and I'm not sure how to deal with it yet. Perhaps we need to make the descriptions in the generated calls to `test_that()` more verbose, so that they contain what previously was part of the context?

**Comment by MichaelChirico** [comment]
isn't that done already?

https://github.com/r-dbi/DBItest/blob/e9286cb4bb963d8cbd5491fda9fcc1e29997a777/R/run.R#L43
