### ISSUE TITLE
Allow "special values" passed as `n` in `dbFetch()`

### ISSUE THREAD

**Issue by nbenn** [r-dbi/DBItest#296]
As per DBI specification a backend may [allow for "special values" to be passed as `n` in `dbFetch()`](https://github.com/r-dbi/DBI/blob/5235cc08703cef8f4754a27084c0581df0a30548/R/dbFetch.R#L23-L26):

> **n** maximum number of records to retrieve per fetch. Use n = -1 or n = Inf to retrieve all pending records. Some implementations may recognize other special values.

Such a "special value" might for example be `NA`. Yet, there are tests that disallow this:

https://github.com/r-dbi/DBItest/blob/2c29217bdd0b3314e6ec65216d99a3bf83a63464/R/spec-result-fetch.R#L54-L64

Generally, such tests should probably be removed. If the specification is narrowed down a bit (to scalar values for examples), some tests may remain.

**Comment by krlmlr** [comment]
Agree. We can skip them for now, with a reference to this issue.
