### ISSUE TITLE
Is it possible to replace `palmerpenguins` or make it optional?

### ISSUE THREAD

**Issue by barracuda156** [r-dbi/DBItest#299]
That package fails to build for us in Macports setup, weirdly, and upstream does not respond since April:
https://github.com/allisonhorst/palmerpenguins/issues/96

We do want `DBItest` to build and work, however.

**Comment by krlmlr** [comment]
Sorry, I don't have the bandwidth to support PPC, and I don't have easy access to this platform. The palmerpenguins package is a simple data package, there should be a way to build it on that platform.

Perhaps it's worth reviewing or reaching out to R-sig-mac? 

https://stat.ethz.ch/pipermail/r-sig-mac/

**Comment by barracuda156** [comment]
@krlmlr This should not be arch-related at all. There is something wrong with the package (penguins, not yours).
We have over 4000 R ports, and all of them build fine on all archs (including PowerPC). And of course, nothing-to-compile packages install fine as long as they are not broken.
I can recall two cases out of thousands of such failures. Penguins is one of these two. (Maybe there was another one, but it is extremely uncommon; I test every package on PPC, so whatever is for R in Macports, does at least build, in most cases all tests pass too.)

**Comment by krlmlr** [comment]
How can we replicate this in a fresh macOS install?

**Comment by barracuda156** [comment]
@krlmlr Ok, I have tried to install in on Sonoma, and sure enough, it fails identically:
```
svacchanda@43-19 ~ % sudo port -v install R-palmerpenguins
Portfile changed since last build; discarding previous state.
--->  Computing dependencies for R-palmerpenguins.
--->  Fetching distfiles for R-palmerpenguins
--->  Verifying checksums for R-palmerpenguins
--->  Checksumming palmerpenguins_0.1.1.tar.gz
--->  Extracting R-palmerpenguins
--->  Extracting palmerpenguins_0.1.1.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_R_R-palmerpenguins/R-palmerpenguins/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/R-palmerpenguins/palmerpenguins_0.1.1.tar.gz' | /usr/bin/tar -xf - 
--->  Configuring R-palmerpenguins
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_R_R-palmerpenguins/R-palmerpenguins/work/palmerpenguins" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes 
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘palmerpenguins’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* re-saving .R files as .rda
Error in loadNamespace(x) : there is no package called ‘palmerpenguins’
Execution halted
Command failed:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_R_R-palmerpenguins/R-palmerpenguins/work/palmerpenguins" && /opt/local/bin/R CMD build . --no-manual --no-build-vignettes 
Exit code: 1
Error: Failed to configure R-palmerpenguins: configure failure: command execution failed
Error: See /opt/local/var/macports/logs/_opt_svacchanda_SonomaPorts_R_R-palmerpenguins/R-palmerpenguins/main.log for details
```

I will make a branch now, then it should be reproducible via `sudo port -v install R-palmerpenguins` (Xcode and Macports are pre-requisites).

**Comment by barracuda156** [comment]
@krlmlr This adds the port: https://github.com/barracuda156/macports-ports/tree/palmerpenguins

I did not try on Intel, but it does fail on aarch64 and ppc.

**Comment by krlmlr** [comment]
Thanks. I'm new to MacPorts, seeing:

```
% sudo port -v install R-palmerpenguins
Error: Port R-palmerpenguins not found
```

**Comment by barracuda156** [comment]
@krlmlr Yes, because it is not in Macports now: I cannot add a port which is broken.

To reproduce this locally, one needs, upon installing Xcode tools and Macports:

1. Make a local port repo (no need to have the whole copy, just one port for penguins from my tree, placed like this: `@local_repo_root@/R/R-palmerpenguins/Portfile`).
2. Edit `/opt/local/etc/macports/sources.conf`, adding a link pointing to your local port repo; please refer to the link above for details. But it is literally add a single line to a text file.
3. Run `sudo port -v sync` to have your locally added port recognized: you will see it being added in the terminal output, as long as port sync is ran with -v.
4. Run `sudo port -v install` for the port in question. Using -v -N will bypass asking if you want dependencies installed.

**Comment by krlmlr** [comment]
Here's what I did:

```sh
cd /Users/kirill
git clone --depth 1 git@github.com:barracuda156/macports-ports.git -b palmerpenguins
# Add file:///Users/kirill/macports-ports/R/R-palmerpenguins to /opt/local/etc/macports/sources.conf, before `rsync::`
sudo port -v sync # Reports 0 new packages
sudo port -v install R-palmerpenguins
# Error: Port R-palmerpenguins not found 
```

Then I cleaned the `macports-ports` of all but `R/R-palmerpenguins` and added `file:///Users/kirill/macports-ports` . Could I also have added `file:///Users/kirill/macports-ports/R` ?

**Comment by barracuda156** [comment]
Here is exactly what I have locally, which works (Macports in installed in its default prefix, `/opt/local/`).

In `/opt/local/etc/macports/sources.conf`:
```
. . .
# override repo
file:///opt/PPCSnowLeopardPorts

rsync://rsync.macports.org/macports/release/tarballs/ports.tar [default]
```
Where the first alias point to an overlay ports repo.

Then, here would be the port for penguins: `/opt/PPCSnowLeopardPorts/R/R-palmerpenguins`.

> file:///Users/kirill/macports-ports/R/R-palmerpenguins to /opt/local/etc/macports/sources.conf

If this is not a typo, this is wrong. Unless I miss something, `file:///Users/kirill/macports-ports` will be the right thing.

**Comment by krlmlr** [comment]
It's now running for a few hours, but also compiling a ton of stuff.

🍿

**Comment by barracuda156** [comment]
Awesome!

P. S. It needs two builds of gcc (runtime and compiler) and some llvm/clangs (depending on the system), so from source it gonna take a while. Normally it will download pre-built ports, unless either `macports.conf` has a custom setting to build from source always, or the system is unsupported on buildbots (being too old or too new). Also `+universal` variants usually do not have pre-built versions.

**Comment by krlmlr** [comment]
Does the order of the repos matter?

**Comment by barracuda156** [comment]
To be honest I never tried to reverse it, since that fails the purpose: as I understand, if the original Macports repo will be above, it will override custom portfiles with default ones (with net zero effect). Presumably if the port only exists in one repo and not another, it should still work. But is there a use case where one would want to set it up that way?

**Comment by krlmlr** [comment]
I could reproduce the error.

For the palmerpenguins package, the presence of the `build/` directory turns out to be fatal. Removing it fixes the issue.

I'm not sure I understand the macports build process. Can you please describe it or point me to code?

**Comment by barracuda156** [comment]
@krlmlr Thank you, this is greatly appreciated.

The code handling `R` stuff specifically sits here: https://github.com/macports/macports-ports/blob/master/_resources/port1.0/group/R-1.0.tcl
(Is that stuff readable?)

Customized stuff should go into the portfile and/or patches.

P. S. It is certainly possible that we have something set up not in an optimal way. If so, we can change the code in the portgroup itself accordingly.

**Comment by krlmlr** [comment]
I'm reading the following:

- download the `.tar.gz` from CRAN
- extract it
- Run `R CMD build .` on the extract
- Then, run `R CMD INSTALL .` in the extracted directory

Please correct me if I misread.

Would it work to install the tarball downloaded from CRAN, without extracting and `R CMD build` ? That's one of the ways that works in other environments.

**Comment by barracuda156** [comment]
Yes, we could try that. In a given set-up, we can override configure stage (to do nothing) and do manual extract by throwing the tarball from distpath to destroot :) Gonna look ugly, but perhaps gonna replicated the described procedure.

I will try now and update you.

(On a side note, I find the whole R build system to be designed by alien species – who even arrived to labeling an action which trivially makes an archive a “build”?)

**Comment by krlmlr** [comment]
Thanks. Do we even need to extract? Can we run `R CMD INSTALL palmerpenguins_x.y.z.tar.gz` ?

The build and installation process has matured over time, it's fine.

**Comment by barracuda156** [comment]
> Do we even need to extract?

Not necessarily in a sense of actually extracting, but we need to trick Macports into thinking it was done :)
Normally there are common stages: fetch, extract, configure, build, destroot, activate. They may be skipped or overridden, but that has to be implemented.

**Comment by barracuda156** [comment]
@krlmlr I guess I have done it. Need to see if it is useful for something still.

**Comment by krlmlr** [comment]
Thanks. The way I see it:

- fetch: download from CRAN
- extract, configure: noop
- build: `R CMD INSTALL .` into temporary library (`R_LIBS_USER` environment variable)
- destroot: what is this?
- activate: copy from temporary library into target location

Wouldn't that simplify the portgroup code by a lot, instead of complicating it? Can we devise a process that works for all packages, without exception?

**Comment by barracuda156** [comment]
Destroot is that temporary location which replicates final destination directory structure but appending destroot to paths. This is what otherwise would be ”install”. Macports handles then everything that ended up in destroot into corresponding final locations.

As for simplification: in principle why not, but without checking specifics I can’t say if it gonna work robustly.
If R was building stuff with build and installing with install, setting everything up would be a piece of cake. Since it is not how it is designed to work, I need to figure out a few things before making radical changes (I mean, no one gonna manually test every of 4k packages):
1. If R build is strictly useless, amounting to packing the archive back, we surely can throw it away. As I understand, however, it is not necessarily the case. If that is correct, what is expected or likely to change?
2. Tests should run in the new config for it to be a viable change (i.e. `port test` wherever supported).
3. One thing which I and some other Macports developers find suboptimal is that currently build is done in destroot stage (well, because R builds and installs with one command). While it works, it makes it impossible to interrupt and resume the build, for example. Not a concern for the end user, but inconvenient for testing or fixing something. Is it possible to separate building and installing? (Ideally configure should also be in its place, but that, I guess, is too much to expect.)

**Comment by krlmlr** [comment]
1. `R CMD build` from an extracted tarball doesn't add value per se, but helps split the build, configuration, and installation stages
2. Tests are typically part of the built package, the tarball you download from CRAN
3. If there is value in separating the building and installation stages, trimming down the extracted CRAN tarball is a viable alternative indeed.

Perhaps then:

- fetch: download from CRAN
- extract: unpack tarball
- configure: Run `./configure`
- build: `R CMD INSTALL . --no-configure` into temporary library (`R_LIBS_USER` environment variable)
- destroot: copy from temporary library into destroot
- activate: do whatever is needed to do

I'm really not sure about why the presence of `build/partial.rdb` breaks palmerpenguins in our case. Deleting it fixes the issue, perhaps it's safest to add an override just for this package and see if other packages have the same problem.

Tests are tricky. `R CMD check` does a few platform-independent quality checks, but also installs the package (again!) in a temporary library. This takes much more time than needed. Tests on an installed package are just a subset of what `R CMD check` does, but we would need to better understand this procedure to pick the relevant bits and run it on an already-built (after "build") package.

**Comment by barracuda156** [comment]
With tests it is indeed unfortunate that, at least currently, it builds a package twice, assuming I wanna a) run tests and then b) install. Normally ports can be installed after running `sudo port test` without another build process.
We do want however to run tests on a newly built package via `port test`.

I can think of some ugly trickery to move sources built in test into the `src` folder (that will work, presumably, since it does work manually), which gonna save from a need to build a package over again, but then it may have unintended consequences with some, less typical packages.

Hopefully a proper solution to this can be found eventually.

**Comment by barracuda156** [comment]
@krlmlr By the way, I got an unrelated to the issue question, but concerning testing of R packages. Maybe you have an idea why BATCH is broken for us? https://trac.macports.org/ticket/67059

Initially I assumed it is broken for PowerPC for a random reason because no one ever tested it there. However I got the same failure then on Sonoma/aarch64.

It may be the case that something is lacking in our R environment, but I just dunno what it needs to work.

**Comment by barracuda156** [comment]
@krlmlr UPD. Both penguins and DBItest are now in Macports. Thank you for helping to sort this out!

Would you like to be a co-maintainer for DBItest? (Does not entail obligations, but you will be informed on PRs related to the port which you can reqiew.)

**Comment by krlmlr** [comment]
I tried `R CMD check` on a binary package built with `R CMD INSTALL --build .`, and, of course,

```
Only *source* packages can be checked.
```

This thread is getting out of hand, I'm glad the issue has been resolved. Would you like to open new, focused issues, in a suitable repo, based on what we discussed here and what you consider relevant?

I don't mind co-maintaining DBItest, just out of curiosity.

**Comment by barracuda156** [comment]
@krlmlr Great, I will add you then to the portfile in the next update.

For the R Portgroup (and how packages are built and installed) I will do some experimenting locally first, if I find a procedure which gonna separate stages in a better way, I will submit that. Not something to do in a hurry, since, penguins aside, our set-up works reliably and is well-tested on different platforms.

P. S. I am happy that you got some interest in R with Macports. Feel free to contribute with new packages, if you wish, and/or improvements to whatever we have.

**Comment by barracuda156** [comment]
@krlmlr Commits https://github.com/macports/macports-ports/commit/bd5c1849adcc746f78c8c4db25068c49e6b0c194 and https://github.com/macports/macports-ports/commit/c5528d07b818b00a7b608a3f31caaad5eacd7da4 add you to maintainers of `DBI` and `DBItest`.
