### ISSUE TITLE
different SQL dialects among DBMS: in test_result: column alias & FROM stmt.)

### ISSUE THREAD

**Issue by marcelboldt** [r-dbi/DBItest#45]
Hi Kirill et all,

I am facing issues in test_result that derive form differences among SQL dialects:
#### a. column alias:

dbSendQuery composes a (temporary) table in the DB, thus `SELECT 1` becomes `CREATE TABLE xy_temp AS (SELECT 1)`. This works for postgres, but e.g. EXASOL and Oracle need a column alias, i.e. `SELECT 1 as a` or `SELECT 1 as "1"` (quoted identifier needed for the first char is numeric)
#### b. FROM statement:

Oracle does not get along with SELECT without FROM stmt, it would need e.g. `SELECT 1 AS a FROM dual`. EXASOL gets along without, except for in combination with a WHERE clause. 

While almost any DBMS should not have problems if col aliases were added, but the dummy table "dual" does not exist everywhere. One option would be to add a parameter to define the table to use. Another would be to have the script create a table in the DBMS before the test and drop it on exit.

My opinion is that that general approach should be to avoid parameters whenever possible (there might be other dialect related issues, adding parameters for everything would cause confusion). Thus I prefer the writing of a table for the test.

Cheers,

Marcel

**Comment by krlmlr** [comment]
Thanks. The first issue should be easy to resolve. For the second issue we might need a configuration argument: `make_context(..., tweaks = list(dummy_table = "DUAL"))`. Temporary setup (e.g., creating such a "DUAL" table) can be done independently of DBItest.

I agree that avoiding parameters is best, but I know at least five engines that make do without the "DUAL" table. Requiring it feels like the wrong way to me.

Would you like to submit a pull request?

**Comment by marcelboldt** [comment]
Sure I would :-) As soon as I have the test running with EXASOL.

**Comment by marcelboldt** [comment]
These two issues have been fixed in my recent pull request, but now there is the next one: quoting of identifiers... postgres converts to lowercase, Oracle to uppercase, some keep it or else...
I will add another tweak-parameter for this.

**Comment by krlmlr** [comment]
@tkilias: I see you have worked on the DBI driver for Exasol recently. Please open a new issue if you think we need to improve in this package.
