### ISSUE TITLE
Identifiers should be quoted

### ISSUE THREAD

**Issue by hoesler** [r-dbi/DBItest#64]
Currently, all tests in DBItest that compare R input to SQL results assume case sensitivity of SQL identifiers:

``` R
fetch_single = function() {
  ...
  query <- "SELECT 1 as a"
  ...
  expect_identical(rows, data.frame(a=1L))
  ...
}
```

The SQL92 specification (section 5.2.13) states, however, that identifiers are case insensitive unless quoted. Therefore, I think that all identifiers should be wrapped with dbQuoteIdentifier(...) to make the test cases more generally applicable (Although for some Databases even this might fail: http://www.alberton.info/dbms_identifiers_and_case_sensitivity.html).

**Comment by krlmlr** [comment]
Thanks. This is unfortunate, I'd prefer a more relaxed comparison (i.e., allow names to differ w.r.t. case). Would it help if identifiers were generally given in uppercase in the queries?

**Comment by hoesler** [comment]
A relaxed comparison could be an option. But what about dbWriteTable() and alike which expect a table name? Are these methods expected to quote the name using dbQuoteIdentifier (unless the name is given as SQL("..."))? Then you still might end up with table lookup failures if you don't quote the name in the select expression. Uppercasing all identifiers will not help here, because some Databases (PostgreSQL) convert unquoted identifiers to lower case.

So, from my perspective, there are two options depending on the default assumption of case:

1. Case insensitive: Methods which have an identifier as an argument, like dbWriteTable, are expected not to quote per default and the test functions ignore case.
2. Case sensitive: Quote all identifiers in expressions.

**Comment by krlmlr** [comment]
I guess dbWriteTable() and dbReadTable() should quote, and the tests should always compare case-insensitive.

**Comment by hoesler** [comment]
People will still run into trouble.

Take H2 for example which converts unquoted identifiers to uppercase:
A table named "test" created with quotes (as done by dbWriteTable) will not be found using an unquoted identifier.
```SQL
create table "test";
select * from "test"; # OK
select * from test; # Table "TEST" not found; ...
```

**Comment by krlmlr** [comment]
- [ ] dbReadTable() et al. should call dbQuoteIdentifier() on the input (rstats-db/DBI#24)
- [ ] we should test dbQuoteIdentifier() very soon (and recommend implementing it first), so that we can quote identifiers in our queries

Other than that I'll try to write the specs generic enough to take potential case mangling into account. If this is not sufficient, we may need to add a tweak.

**Comment by krlmlr** [comment]
The specs now require that `dbWriteTable()` and `dbReadTable()` quotes their `name` argument. Please open a new issue if you think there's more to do here.
