### ISSUE TITLE
Test MonetDB and MonetDBlite in Travis CI

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBItest#71]
Follow-up to #52, to make sure that DBItest updates do not break too much of existing code.

**Comment by krlmlr** [comment]
@hannesmuehleisen: I guess we can close this? Is DuckDB + DBItest tested on Travis?

**Comment by hannesmuehleisen** [comment]
Yes, see https://github.com/cwida/duckdb/blob/master/tools/rpkg/tests/testthat/test-DBItest.R
