### ISSUE TITLE
Use enc package for encoding checks

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBItest#82]
Follow-up to #72.

**Comment by aryoda** [comment]
Do you have a link to the `utf8` package (I cannot find such a package at CRAN)? I am trying to write a unit test for a related problem in the `odbc` package (https://github.com/rstats-db/odbc/issues/56) and discovered that the `DBItest` package is a good place for reusable unit tests around DBI...

**Comment by krlmlr** [comment]
It's currently on GitHub only. The issue you pointed to looks like an issue with the connection or database encoding, not sure how helpful the utf8 package will be.

**Comment by krlmlr** [comment]
No longer relevant.
